version: "3"
services:
  postgresql:
    image: postgres
    restart: always
    container_name: moin-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moin_db
    ports:
      - 15432:5432
  redis:
    image: redis
    restart: always
    container_name: moin-redis
    ports:
      - 16379:6379
